name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "30 01 * * *"}]
  workflow_dispatch:
  push:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@366f8b9dfe3a59656c67d5dcad9950f59c9bc96d
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Berlin
          base_indepth: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_limit: 0
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
